stages:
    - build
    - test
    - sonar
before_script:
    - echo "Start CI"
build:
    stage: build
    script:
        - cd digitalmarketplace
        - ./gradlew assemble  
test:
    stage: test
    script:
        - cd digitalmarketplace
        - ./gradlew clean test
sonar:
    stage: sonar
    script:
        - cd digitalmarketplace
        - ./gradlew sonarqube -D sonar.projectKey=bludevil-digitalmarketplace -D sonar.host.url=%SONAR_URL% -D sonar.login=%SONAR_LOGIN%
after_script:
  - echo "End CI"
