stages:
    - build
    - test
    - sonar
    - deploy-docker
before_script:
    - echo "Start CI/CD"
build:
    stage: build
    script:
        - cd digitalmarketplace
        - ./gradlew assemble  
test:
    stage: test
    script:
        - cd digitalmarketplace
        - ./gradlew clean test --info
sonar:
    stage: sonar
    script:
        - cd digitalmarketplace
        - ./gradlew sonarqube -D sonar.projectKey=bludevil-digitalmarketplace -D sonar.host.url="$SONAR_URL" -D sonar.login="$SONAR_LOGIN"
deploy-docker:
    stage: deploy-docker
    only:
        - master
    before_script:
        - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASS"
        - cd digitalmarketplace
        - ./gradlew bootJar
    script:
        - docker-compose build
        - docker-compose push
after_script:
  - echo "End CI/CD"
