before_script:
    - echo "Start CI"
build:
    stage: build
    script:
        - cd digitalmarketplace
        - ./gradlew assemble  
test:
    stage: test
    script:
        - cd digitalmarketplace
        - ./gradlew clean test
after_script:
  - echo "End CI"
