stages:
    - build
    - sonar
    - test
before_script:
    - echo "Start CI"
build:
    stage: build
    script:
        - cd digitalmarketplace
        - ./gradlew assemble  
sonar:
    stage: sonar
    script:
        - cd digitalmarketplace
        - ./gradlew sonarqube -Dsonar.projectKey="bludevil-digitalmarketplace" -Dsonar.host.url=%SONAR_URL% -Dsonar.login=%SONAR_LOGIN%
test:
    stage: test
    script:
        - cd digitalmarketplace
        - ./gradlew clean test
after_script:
  - echo "End CI"
